
#ifndef CONSTANTS_H
#define CONSTANTS_H

#define WIDTH 800
#define HEIGHT 600
#define FPS 100

#define ASTRONOMIC_UNIT 100.0f

#define SUN_RADIUS (EARTH_RADIUS * 109)
#define SUN_AXIS_HALFSIZE 0.25f
#define EARTH_RADIUS (ASTRONOMIC_UNIT * 4.2e-5)
#define EARTH_AXIS_HALFSIZE 0.13f
#define SIDERIAL_YEAR 365.3f

#define ECLIPTIC_INCLINATION 7.2f
#define EARTH_AXIS_INCLINATION 23.5f

#define MOON_RADIUS (EARTH_RADIUS * 0.273)
#define MOON_INCLINATION 5.1f
#define SIDERIAL_MONTH 27.3f
#define MOON_ORBIT_RADIUS (ASTRONOMIC_UNIT * 0.002)

#define SUN_SIDERIAL_PERIOD 25.0f

#define DAYS_PER_SECOND 0.001f

#endif
