
#ifndef CONSTANTS_H
#define CONSTANTS_H

#define FPS 60

#define SUN_RADIUS 0.15f
#define SUN_AXIS_HALFSIZE 0.25f
#define EARTH_RADIUS 0.07f
#define EARTH_AXIS_HALFSIZE 0.13f
#define SIDERIAL_YEAR 365.3f

#define ECLIPTIC_INCLINATION 7.2f
#define EARTH_AXIS_INCLINATION 23.5f

#define MOON_RADIUS 0.02f
#define MOON_INCLINATION 5.1f
#define SIDERIAL_MONTH 27.3f
#define MOON_ORBIT_RADIUS 0.13f

#define SUN_SIDERIAL_PERIOD 25.0f

#define DAYS_PER_SECOND 1.0f

#endif
