
SOURCES = main.cpp rendering.cpp bmp_loader.cpp planet.cpp
OBJECTS = $(SOURCES:.cpp=.obj)

CL = cl
LINK = link
CXXFLAGS = /nologo /EHsc /MD /Iinclude
LDFLAGS = /nologo /LIBPATH:lib /SUBSYSTEM:windows
LIBS = SDL2.lib SDL2main.lib SDL2_ttf.lib opengl32.lib glu32.lib

all: solar

.cpp.obj:
	$(CL) $(CXXFLAGS) /c $< /Fo$@

solar: $(OBJECTS)
	$(LINK) $(LDFLAGS) $** $(LIBS) /OUT:$@.exe

clean:
	del *.obj *.exe

.PHONY: clean
