
SOURCES = main.cpp rendering.cpp bmp_loader.cpp planet.cpp
OBJECTS = $(SOURCES:.cpp=.obj)

CL = cl
LINK = link
CXXFLAGS = /nologo /EHsc /Ifreeglut/include
LDFLAGS = /nologo /LIBPATH:freeglut/lib

all: solar

.cpp.obj:
	$(CL) $(CXXFLAGS) /c $< /Fo$@

solar: $(OBJECTS)
	$(LINK) $(LDFLAGS) $** $(LIBS) /OUT:$@.exe

clean:
	del *.obj *.exe

.PHONY: clean
